#Data store options 
# if both are false, copyrights will not persist past restart
# if both are true, copyrights will be synced between them at plugin startup
useFlatFileStorage: true
useSQL: false
MySQL: # For copyright storage
  address: 0.0.0.0
  port: 3306
  database: database1
  username: database1
  password: 'password'

#Messages
msg:
  NoCommandPerms: "&cYou do not have permission to use this command"
  NoCopyPerms: "&aYou do not have permission to copy this map"
  NoBannerPerms: "&cYou cannot modify banners on this map without trust"
  NotPlayer: "&cMust be a Player to use this command"
  InvalidSubCommand: "&cCommand not valid, for assistance, use /copyright help"
  PlayerNotFound: "&cPlayer Not Found"
  GiveFullTrust: "&aFull Trust given to {ign}"
  TakeFullTrust: "&aFull Trust removed from {ign}"
  GiveFullTrustPublic: "&aGranted full trust to public"
  TakeFullTrustPublic: "&aFull trust removed from public"
  FullTrustList:
    Owner: "&bFull trust list for {ign}"
    List: "&bTrusted: {trustlist}"
    Public: "&bPublic: {public}"
  HoldingLockedMap: "&cMust be holding locked map"
  AddCopyright: "&aCopyright added"
  DeleteCopyright: "&aCopyright deleted"
  CopyrightAlreadyExists: "&cMap already copyrighted"
  MapNotCopyrighted: "&eThis map is not copyrighted"
  NotOwner: "&cYou are not the copyright owner"
  GiveTrust: "&a{ign} has been given trust"
  TakeTrust: "&a{ign} is no longer trusted"
  GiveOwner: "&aCopyright ownership given to {ign}"
  GivePublicTrust: "&aPublic trust added"
  TakePublicTrust: "&aPublic trust removed"
  Info:
    MapID: "&bCopyright Info for Map ID {mapid}"
    Owner: "&bOwner: {ign}"
    TrustList: "&bTrusted: {trustlist}"
    Public: "&bPublic: {public}"
  Area:
    NoPerms: "&cYou do not have permission to make a map in this area"
    NotClaimed: "&eArea not Claimed"
    AlreadyClaimed: "&cArea already claimed"
    AddClaim: "&aArea successfully claimed"
    DeleteClaim: "&aArea successfully unclaimed"
    NotOwner: "&cYou are not the area owner"
    GiveTrust: "&a{ign} trusted to make maps in area"
    TakeTrust: "&a{ign} no longer trusted to make maps in area"
    GivePublicTrust: "&aPublic trusted to make maps in area"
    TakePublicTrust: "&aPublic no longer trusted to make maps in area"
    AreaBroken: "&cArea claim info corrupted, area info deleted, please reclaim area"
    Info:
      Owner: "&bOwner: {ign}"
      TrustList: "&bTrusted: {trustlist}"
      Public: "&bPublic: {public}"
  Help:
    PageNotFound: "&cMap Copyright Help Page {pagenumber} not found"
    1:
      - "&6Map Copyright Help Page 1"
      - "&aWhenever you lock a map, MapCopyright will automatically give you the copyright stopping others from making copies"
      - "&aYou can also use MapCopyright to claim map areas stopping others from making new maps of the area"
      - "&aUsing /copyright, you can control who make copies of your maps or areas or use fulltrust to give someone permission on all your areas and maps"
      - "&6/copyright help 2 to go to page 2"
    2:
      - "&6Map Copyright Help Page 2"
      - "&aThe subcommands of /copyright are:"
      - "&aarea - Control map area permissions, page 4 for more info"
      - "&acreate - Create a new copyright for the held map"
      - "&adelete - Delete the copyright for the held map"
      - "&afulltrust - control who has full trust for your areas and maps, page 6 for more info"
      - "&agive <ign> - Give ownership of the held map"
      - "&ainfo - Get info about the held map's copyright"
      - "&6/copyright help 3 to go to page 3"
    3:
      - "&6Map Copyright Help Page 3"
      - "&atogglepublic - Make the held map public so everybody can copy it"
      - "&atrust <ign> - Give someone permission to make copies of the held map"
      - "&auntrust <ign> - Remove trust from the player for the held map"
      - "&6/copyright help 4 to go to page 4"
    4:
      - "&6Map Copyright Help Page 4"
      - "&a/copright area - used to manage permissions for the 8 chunk x 8 chunk map area you are currently standing in"
      - "&aThis is the area that will appear when a map is filled"
      - "&aArea permissions are used to stop other players from making maps of the area"
      - "&aPlayers with your fulltrust can still make new maps in claimed areas"
      - "&aSubcommands on next page"
      - "&6/copyright help 5 to go to page 5"
    5:
      - "&6Map Copyright Help Page 5"
      - "&aArea subcommands used /copyright area <subcommand>:"
      - "&aclaim - Claim this map area"
      - "&ainfo - Get info about this map area"
      - "&atogglepublic - Allow all players to make new maps here"
      - "&atrust <ign> - Give someone permission to make new maps in this area"
      - "&aunclaim - Unclaim this map area"
      - "&auntrust <ign> - Remove trust from a player"
      - "&6/copyright help 6 to go to page 6"
    6:
      - "&6Map Copyright Help Page 6"
      - "&aFull trust is used to give a player permission to copy any maps you own and make new maps in any area you own"
      - "&aSubcommands used as /copyright fulltrust <subcommand>:"
      - "&aadd <ign> - Give someone full trust"
      - "&alist - List all players with your full trust"
      - "&aremove <ign> - Take full trust away"
      - "&atogglepublic - Give everybody full trust"