#Data store options 
# if both are false, copyrights will not persist past restart
# if both are true, copyrights will be synced between them at plugin startup
useFlatFileStorage: true
useSQL: false
MySQL: # For copyright storage
  address: 0.0.0.0
  port: 3306
  database: database1
  username: database1
  password: 'password'

#Messages
msg:
  NoCommandPerms: "&cYou do not have permission to use this command"
  NoCopyPerms: "&aYou do not have permission to copy this map"
  NoBannerPerms: "&cYou cannot modify banners on this map without trust"
  NotPlayer: "&cMust be a Player to use this command"
  InvalidSubCommand: "&cCommand not valid, for assistance, use /copyright help"
  PlayerNotFound: "&cPlayer Not Found"
  GiveFullTrust: "&aFull Trust given to {ign}"
  TakeFullTrust: "&aFull Trust removed from {ign}"
  GiveFullTrustPublic: "&aGranted full trust to public"
  TakeFullTrustPublic: "&aFull trust removed from public"
  FullTrustList:
    Owner: "&bFull trust list for {ign}"
    List: "&bTrusted: {trustlist}"
    Public: "&bPublic: {public}"
  HoldingLockedMap: "&cMust be holding locked map"
  AddCopyright: "&aCopyright added"
  DeleteCopyright: "&aCopyright deleted"
  CopyrightAlreadyExists: "&cMap already copyrighted"
  MapNotCopyrighted: "&eThis map is not copyrighted"
  NotOwner: "&cYou are not the copyright owner"
  GiveTrust: "&a{ign} has been given trust"
  TakeTrust: "&a{ign} is no longer trusted"
  GiveOwner: "&aCopyright ownership given to {ign}"
  GivePublicTrust: "&aPublic trust added"
  TakePublicTrust: "&aPublic trust removed"
  Info:
    MapID: "&bCopyright Info for Map ID {mapid}"
    Owner: "&bOwner: {ign}"
    TrustList: "&bTrusted: {trustlist}"
    Public: "&bPublic: {public}"
  Area:
    NoPerms: "&cYou do not have permission to make a map in this area"
    NotClaimed: "&eArea not Claimed"
    AlreadyClaimed: "&cArea already claimed"
    AddClaim: "&aArea successfully claimed"
    DeleteClaim: "&aArea successfully unclaimed"
    NotOwner: "&cYou are not the area owner"
    GiveTrust: "&a{ign} trusted to make maps in area"
    TakeTrust: "&a{ign} no longer trusted to make maps in area"
    GivePublicTrust: "&aPublic trusted to make maps in area"
    TakePublicTrust: "&aPublic no longer trusted to make maps in area"
    AreaBroken: "&cArea claim info corrupted, area info deleted, please reclaim area"
    Info:
      Owner: "&bOwner: {ign}"
      TrustList: "&bTrusted: {trustlist}"
      Public: "&bPublic: {public}"
  Help:
    PageNotFound: "&cMap Copyright Help Page {pagenumber} not found"
    1:
      - "&aMap Copyright Help Page 1"
      - "&dWhen you lock a map, MapCopyright creates a copyright, preventing copies from being made."
      - "&dMapCopyright also protects map areas preventing others from creating new maps."
      - "&dTo control copyrights and areas, use /copyright <subcommand>"
      - "&dSubcommands are listed on page 2 and 3."
      - "&aNext page: /copyright help 2"
    2:
      - "&aMap Copyright Help Page 2"
      - "&dSubcommands: use /copyright <subcommand>:"
      - "&darea - Control map area permissions. (See page 4 for more info)"
      - "&dcreate - Creates a new copyright for the held map."
      - "&ddelete - Deletes the copyright for the held map."
      - "&dfulltrust - control who has full trust over areas and maps. (See page 6 for more info)."
      - "&dgive <ign> - Give ownership of the held map to that user."
      - "&dinfo - Get info about the held map's copyright."
      - "&aNext page: /copyright help 3"
    3:
      - "&aMap Copyright Help Page 3"
      - "&dSubcommands continued..."
      - "&dtogglepublic - Make the held map public so everybody can copy it."
      - "&dtrust <ign> - Give someone permission to make copies of the held map."
      - "&duntrust <ign> - Remove trust from the player for the held map."
      - "&aNext page: /copyright help 4"
    4:
      - "&aMap Copyright Help Page 4"
      - "&d/copright area - used to manage permissions for the 8x8 chunk map area you are currently standing in."
      - "&dThis is the area that will appear when a map is filled."
      - "&dArea permissions are used to stop map creation in the area."
      - "&dPlayers with your fulltrust can still make new maps in claimed areas."
      - "&dSubcommands on next page..."
      - "&aNext page: /copyright help 5"
    5:
      - "&aMap Copyright Help Page 5"
      - "&dArea Subcommands: use /copyright area <subcommand>:"
      - "&dclaim - Claim this map area."
      - "&dinfo - Get info about this map area."
      - "&dtogglepublic - Allow all players to make new maps here."
      - "&dtrust <ign> - Give someone permission to make new maps in this area"
      - "&dunclaim - Unclaim this map area."
      - "&duntrust <ign> - Remove trust from a player."
      - "&aNext page: /copyright help 6"
    6:
      - "&aMap Copyright Help Page 6"
      - "&dFull Trust is used to give a player permission to copy any maps you own and make new maps in any area you own."
      - "&dFulltrust Subcommands: use as /copyright fulltrust <subcommand>:"
      - "&dadd <ign> - Give player full trust."
      - "&dlist - List all players with your full trust."
      - "&dremove <ign> - Take full trust away from player."
      - "&dtogglepublic - Give everybody full trust."
      - "&aLast Page"