#Data store options 
# if both are false, copyrights will not persist past restart
# if both are true, copyrights will be synced between them at plugin startup
useFlatFileStorage: true
useSQL: false
MySQL: # For copyright storage
  address: 0.0.0.0
  port: 3306
  database: database1
  username: database1
  password: 'password'

manageInvisibleItemFrames: true
InvisibleItemFrame:
  ==: org.bukkit.inventory.ItemStack
  v: 3120
  type: ITEM_FRAME
  meta:
    ==: ItemMeta
    meta-type: ENTITY_TAG
    internal: H4sIAAAAAAAA/+NiYOBi4HTNK8ksqQxJTGdk4PTMK8sszkzKSWVkYAAAwtH3ph4AAAA=

#Messages
msg:
  NoCommandPerms: "&cYou do not have permission to use this command"
  NoCopyPerms: "&aYou do not have permission to copy this map"
  NoBannerPerms: "&cYou cannot modify banners on this map without trust"
  NotPlayer: "&cMust be a Player to use this command"
  InvalidSubCommand: "&cCommand not valid, for assistance, use /copyright help"
  PlayerNotFound: "&cPlayer Not Found"
  GiveFullTrust: "&aFull Trust given to {ign}"
  TakeFullTrust: "&aFull Trust removed from {ign}"
  GiveFullTrustPublic: "&aGranted full trust to public"
  TakeFullTrustPublic: "&aFull trust removed from public"
  FullTrustList:
    Owner: "&bFull trust list for {ign}"
    List: "&bTrusted: {trustlist}"
    Public: "&bPublic: {public}"
  HoldingLockedMap: "&cMust be holding locked map"
  AddCopyright: "&aCopyright added"
  DeleteCopyright: "&aCopyright deleted"
  CopyrightAlreadyExists: "&cMap already copyrighted"
  MapNotCopyrighted: "&eThis map is not copyrighted"
  NotOwner: "&cYou are not the copyright owner"
  GiveTrust: "&a{ign} has been given trust"
  TakeTrust: "&a{ign} is no longer trusted"
  GiveOwner: "&aCopyright ownership given to {ign}"
  GivePublicTrust: "&aPublic trust added"
  TakePublicTrust: "&aPublic trust removed"
  Info:
    MapID: "&bCopyright Info for Map ID {mapid}"
    Owner: "&bOwner: {ign}"
    TrustList: "&bTrusted: {trustlist}"
    Public: "&bPublic: {public}"
  Area:
    NoPerms: "&cYou do not have permission to make a map in this area"
    NotClaimed: "&eArea not Claimed"
    AlreadyClaimed: "&cArea already claimed"
    AddClaim: "&aArea successfully claimed"
    DeleteClaim: "&aArea successfully unclaimed"
    NotOwner: "&cYou are not the area owner"
    GiveTrust: "&a{ign} trusted to make maps in area"
    TakeTrust: "&a{ign} no longer trusted to make maps in area"
    GivePublicTrust: "&aPublic trusted to make maps in area"
    TakePublicTrust: "&aPublic no longer trusted to make maps in area"
    AreaBroken: "&cArea claim info corrupted, area info deleted, please reclaim area"
    Info:
      Owner: "&bOwner: {ign}"
      TrustList: "&bTrusted: {trustlist}"
      Public: "&bPublic: {public}"
  Help:
    PageNotFound: "&cMap Copyright Help Page {pagenumber} not found"
    1:
      - "&aMap Copyright Help Page 1"
      - "&dWhen you lock a map, MapCopyright makes a copyright for you."
      - "&dYou can control who can make copies of your copyrighted map."
      - "&dYou can claim 8x8 chunk map areas and control map creation."
      - "&dTo control copyrights and areas, use"
      - "&3/copyright <subcommand>"
      - "&dSubcommands are listed on page 2 and 3."
      - "&aNext page: /copyright help 2"
    2:
      - "&aMap Copyright Help Page 2"
      - "&dSubcommands: use &3/copyright <subcommand>&d:"
      - "&3area &d- See help page 4."
      - "&3create &d- Creates a new copyright for the held map."
      - "&3delete &d- Deletes the copyright for the held map."
      - "&3fulltrust &d- See help page 6."
      - "&3give <ign> &d- Give ownership of the held map."
      - "&3info &d- Get info about the held map's copyright."
      - "&aNext page: /copyright help 3"
    3:
      - "&aMap Copyright Help Page 3"
      - "&dSubcommands continued..."
      - "&3togglepublic &d- Allow everybody to make copies of the held map."
      - "&3trust <ign> &d- Allow someone to make copies of the held map."
      - "&3untrust <ign> &d- Remove ability to make copies of the held map."
      - "&aNext page: /copyright help 4"
    4:
      - "&aMap Copyright Help Page 4"
      - "&dArea protection allows players to claim 8x8 chunk map areas."
      - "&dThis is the area that will appear when a map is filled."
      - "&dYou can control who can create maps in claimed map areas."
      - "&dArea commands affect the map area you are standing in."
      - "&dArea subcommands on next page..."
      - "&aNext page: /copyright help 5"
    5:
      - "&aMap Copyright Help Page 5"
      - "&dArea Subcommands: use &3/copyright area <subcommand>&d:"
      - "&3claim &d- Claim this map area."
      - "&3info &d- Get info about this map area."
      - "&3togglepublic &d- Allow all players to make new maps here."
      - "&3trust <ign> &d- Allow someone to make new maps in this area"
      - "&3unclaim &d- Unclaim this map area."
      - "&3untrust <ign> &d- Remove trust from a player."
      - "&aNext page: /copyright help 6"
    6:
      - "&aMap Copyright Help Page 6"
      - "&dFull Trust is used to give a player permission to copy any maps you own and make new maps in any area you own."
      - "&dFulltrust Subcommands: use &3/copyright fulltrust <subcommand>&d:"
      - "&3add <ign> &d- Give someone full trust."
      - "&3list &d- List all players with your full trust."
      - "&3remove <ign> &d- Take full trust away from someone."
      - "&3togglepublic &d- Give everybody full trust."
      - "&aLast Page"